{% set version = '10.1.0' %}

package:
  name: gcc-{{ environ.get('TOOLCHAIN_ARCH') }}-elf-newlib
  version: {{ version }}

source:
  - url: http://ftp.gnu.org/gnu/gcc/gcc-{{ version }}/gcc-{{ version }}.tar.xz
    fn: gcc-{{ version }}.tar.gz
    sha256: b6898a23844b656f1b68691c5c012036c2e694ac4b53a8918d4712ad876e7ea2
    folder: gcc
  - url: http://sourceware.org/pub/newlib/newlib-3.3.0.tar.gz
    fn: newlib-3.3.0.tar.gz
    sha256: 58dd9e3eaedf519360d92d84205c3deef0b3fc286685d1c562e245914ef72c66
    folder: newlib

build:
  detect_binary_files_with_prefix: False
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - TOOLCHAIN_ARCH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.15.0
    - cloog
    # Arch specific
    - binutils-{{ environ.get('TOOLCHAIN_ARCH') }}-elf
    - gcc-{{ environ.get('TOOLCHAIN_ARCH') }}-elf-nostdc {{ version }}.*
  run:
    - binutils-{{ environ.get('TOOLCHAIN_ARCH') }}-elf
    - gcc-{{ environ.get('TOOLCHAIN_ARCH') }}-elf-nostdc {{ version }}.*

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
