{% set version = '10.1' %}

package:
  name: gdb-{{ environ.get('TOOLCHAIN_ARCH') }}-elf
  version: {{ version }}

source:
  fn: gdb-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/gdb/gdb-{{ version }}.tar.xz
  sha256: f82f1eceeec14a3afa2de8d9b0d3c91d5a3820e23e0a01bbb70ef9f0276b62c0

build:
  detect_binary_files_with_prefix: True
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - TOOLCHAIN_ARCH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils-{{ environ.get('TOOLCHAIN_ARCH') }}-elf
    - gcc-{{ environ.get('TOOLCHAIN_ARCH') }}-elf-nostdc
    - make
    - pkg-config
    - texinfo
  host:
    - expat
    - mpfr >=2.4.2
    - ncurses
    - xz
    - zlib
  run:
    - binutils-{{ environ.get('TOOLCHAIN_ARCH') }}-elf
    - expat
    - mpfr >=2.4.2
    - ncurses
    - zlib

test:
  commands:
    - {{ environ.get('TOOLCHAIN_ARCH') }}-elf-gdb --version
    - {{ environ.get('TOOLCHAIN_ARCH') }}-elf-gdb --version 2>&1 | grep -q {{ version }}

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL
  summary: 'GDB, the GNU Project debugger, allows you to see what is going on "inside" another program while it executes -- or what another program was doing at the moment it crashed.'
