{% set version = '9.2.0' %}
{% set binutilsversion = '2.34' %}

package:
  name: gcc-{{ environ.get('TOOLCHAIN_ARCH') }}-linux-musl
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/binutils/binutils-{{ binutilsversion }}.tar.xz
    fn: binutils-{{ binutilsversion }}.tar.bz2
    sha256: f00b0e8803dc9bab1e2165bd568528135be734df3fabf8d0161828cd56028952
    folder: binutils
  - git_url: https://github.com/mithro/kernel-headers.git
    git_rev: master
    folder: kernel-headers
  - url: http://ftp.gnu.org/gnu/gcc/gcc-{{ version }}/gcc-{{ version }}.tar.xz
    fn: gcc-{{ version }}.tar.gz
    sha256: ea6ef08f121239da5695f76c9b33637a118dcf63e24164422231917fa61fb206
    folder: gcc
  - git_url: git://git.musl-libc.org/musl
    git_rev: ac304227bb3ea1787d581f17d76a5f5f3abff51f
    folder: musl
{% if 'riscv' in environ.get('TOOLCHAIN_ARCH') %}
    patches:
     - 0001-20190519-merge-riscv.patch
{% endif %}

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - TOOLCHAIN_ARCH
  detect_binary_files_with_prefix: False
  binary_relocation:
    - 'bin/*'
    - 'lib/*.so*'
    - 'libexec/**/*.so*'
    - 'libexec/**/cc1*'
    - 'libexec/**/collect2'
    - 'libexec/**/gcc'
    - 'libexec/**/lto*'
    - 'libexec/**/plugin/gengtype'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - texinfo
  host:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.15.0
    - cloog
  run:
    - isl
    - mpc

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
