{% set version = '2.34' %}

package:
  name: binutils-{{ environ.get('TOOLCHAIN_ARCH') }}-elf
  version: {{ version }}

source:
  fn: binutils-{{ version }}.tar.bz2
  url: https://ftp.gnu.org/gnu/binutils/binutils-{{ version }}.tar.xz
  sha256: f00b0e8803dc9bab1e2165bd568528135be734df3fabf8d0161828cd56028952

build:
  # number: 202002272218
  number: {{ environ.get('DATE_NUM') }}
  # string: 20200227_2218
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - TOOLCHAIN_ARCH

requirements:
  build:
   - texinfo
   - {{ compiler('c') }}
  run:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

test:
  commands:
    - {{ environ.get('TOOLCHAIN_ARCH') }}-elf-ld --version
    - {{ environ.get('TOOLCHAIN_ARCH') }}-unknown-elf-ld --version
    - {{ environ.get('TOOLCHAIN_ARCH') }}-elf-ld --version 2>&1 | grep -q {{ version }}

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL
  summary: 'A set of programming tools for creating and managing binary programs, object files, libraries, profile data, and assembly source code.'
