name: Build packages

on:
  workflow_call:
    secrets:
      ANACONDA_TOKEN:
        description: 'Anaconda Token'
      ANACONDA_USER:
        description: 'Anaconda User'

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}

defaults:
  run:
    shell: bash

jobs:

  #1
  libisl-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "lib/isl"
      OS_NAME: "linux"
      SKIP: "true"  # See https://github.com/hdl/conda-compilers/issues/34
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #2
  binutils-or1k-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #3
  gcc-nostdc-or1k-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-or1k-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #4
  gcc-newlib-or1k-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-or1k-linux", "gcc-nostdc-or1k-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #5
  gcc-musl-or1k-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #6
  gdb-or1k-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-or1k-linux", "gcc-nostdc-or1k-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #7
  binutils-riscv32-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #8
  gcc-nostdc-riscv32-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-riscv32-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #9
  gcc-newlib-riscv32-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-riscv32-linux", "gcc-nostdc-riscv32-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #10
  gcc-musl-riscv32-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #11
  gdb-riscv32-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-riscv32-linux", "gcc-nostdc-riscv32-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #12
  binutils-riscv64-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #13
  gcc-nostdc-riscv64-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-riscv64-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #14
  gcc-newlib-riscv64-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-riscv64-linux", "gcc-nostdc-riscv64-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #15
  gcc-musl-riscv64-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #16
  gdb-riscv64-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-riscv64-linux", "gcc-nostdc-riscv64-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #17
  binutils-lm32-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #18
  gcc-nostdc-lm32-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-lm32-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #19
  gcc-newlib-lm32-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-lm32-linux", "gcc-nostdc-lm32-linux"]
    env:
      PACKAGE: "gcc/newlib"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #20
  gdb-lm32-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-lm32-linux", "gcc-nostdc-lm32-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #21
  binutils-ppc64le-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #22
  gcc-musl-ppc64le-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #23
  binutils-sh-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "binutils"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #24
  gcc-nostdc-sh-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-sh-linux"]
    env:
      PACKAGE: "gcc/nostdc"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #25
  gcc-musl-sh-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #26
  gdb-sh-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libisl-linux", "binutils-sh-linux", "gcc-nostdc-sh-linux"]
    env:
      PACKAGE: "gdb"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #27
  toolchain-or1k-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #28
  toolchain-riscv32-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #29
  toolchain-riscv64-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #30
  toolchain-sh-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "toolchain/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #31
  libisl-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/isl"
      OS_NAME: "osx"
      SKIP: "true"  # See https://github.com/hdl/conda-compilers/issues/34
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #32
  binutils-riscv32-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #33
  binutils-riscv64-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #34
  binutils-lm32-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "lm32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #35
  binutils-ppc64le-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "binutils"
      OS_NAME: "osx"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #36
  sdcc-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "sdcc"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #37
  sdcc-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "sdcc"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - run: brew install coreutils boost
      - uses: hdl/conda-eda/ci@master

  #38
  sdcc-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "sdcc"
      OS_NAME: "windows"
      SKIP: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #39
  # gcc-newlib-sh-linux:
  #   runs-on: "ubuntu-20.04"
  #   needs: ["libisl-linux", "binutils-sh-linux", "gcc-nostdc-sh-linux"]
  #   env:
  #     PACKAGE: "gcc/newlib"
  #     OS_NAME: "linux"
  #     TOOLCHAIN_ARCH: "sh"
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: hdl/conda-eda/ci@master
