name: Build packages

on:
  push:
  workflow_call:
    secrets:
      ANACONDA_TOKEN:
        description: 'Anaconda Token'
      ANACONDA_USER:
        description: 'Anaconda User'

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}

defaults:
  run:
    shell: bash

jobs:

  #1
  libisl-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "lib/isl"
      OS_NAME: "linux"
      SKIP: "true"  # See https://github.com/hdl/conda-compilers/issues/34
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #5
  gcc-musl-or1k-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "or1k"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #10
  gcc-musl-riscv32-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv32"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #15
  gcc-musl-riscv64-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "riscv64"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #22
  gcc-musl-ppc64le-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "ppc64le"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #25
  gcc-musl-sh-linux:
    runs-on: "ubuntu-20.04"
    needs: "libisl-linux"
    env:
      PACKAGE: "gcc/linux-musl"
      OS_NAME: "linux"
      TOOLCHAIN_ARCH: "sh"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master
