name: Upload packages

on:
  push:
    # Prevents triggering multiple workflows in PRs. Workflows triggered from
    # the same commit shouldn't run simultaneously because they're overwriting
    # each other's packages on Anaconda.
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
  OS_NAME: linux
  CI_SCRIPTS_REL_PATH: "conda-eda"

jobs:


  Build:
    uses: ./.github/workflows/Build.yml


  Upload:
    needs: Build
    if: always() && (github.event_name != 'pull_request') && (github.ref == 'refs/heads/master')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: hdl/conda-eda
          ref: master
          path: ${{ env.CI_SCRIPTS_REL_PATH }}
      - run: |
          # Required internally by the scripts to locate other scripts.
          export CI_SCRIPTS_PATH="$GITHUB_WORKSPACE/$CI_SCRIPTS_REL_PATH/ci"
          "$CI_SCRIPTS_PATH"/install.sh
          "$CI_SCRIPTS_PATH"/upload-packages.sh


  Cleanup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: hdl/conda-eda
          ref: master
          path: ${{ env.CI_SCRIPTS_REL_PATH }}
      - run: |
          # Required internally by the scripts to locate other scripts.
          export CI_SCRIPTS_PATH="$GITHUB_WORKSPACE/$CI_SCRIPTS_REL_PATH/ci"
          "$CI_SCRIPTS_PATH"/install.sh
          "$CI_SCRIPTS_PATH"/cleanup-anaconda.sh
